# Generated by Django 2.2.22 on 2021-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='router_specifications')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
